### PR TITLE
Review chapter "HTTP and curl"

### PR DESCRIPTION
**Pull request by ludelafo**

### CODE REVIEW

**Comment by ludelafo** [comment]
I have difficulties explaining the topic of stateful/stateless applications. Do you have an idea on how to improve that part of the chapter @hadrylouis, @GeraudSilvestri, @CamilleKoestli?

ChatGPT gave me the following ideas but I'm still not convinced it's very helpful:

Prompt: How to explain stateful and stateless in computer science to Bachelor students?

ChatGPT said:

When explaining stateful and stateless in computer science to bachelor students, it’s helpful to use simple analogies and examples they can relate to. Here's how you can break it down:

1. Define the Terms
    - Stateful: A system, application, or protocol is stateful if it keeps track of information (state) about a user or process between interactions.
        Example: A shopping cart on an e-commerce site remembers what items you’ve added.
    - Stateless: A system, application, or protocol is stateless if it does not keep any information about previous interactions. Every interaction is independent.
        Example: A vending machine doesn’t remember what you tried to buy earlier; it only responds to your current input.
2. Use Analogies
    - Stateful: It’s like a waiter who remembers your order as you go through a multi-course meal.
    - Stateless: It’s like a food counter at a fast-food restaurant where they don’t remember you. You have to give your full order every time.
3. Explain in Technical Contexts
    - Stateful Example: A TCP connection is stateful because it maintains a session between the client and the server, remembering information like sequence numbers.
    - Stateless Example: HTTP is stateless because each request from the client to the server is independent. That’s why mechanisms like cookies or session tokens are needed to add state.
4. Show Real-Life Applications
    - Stateful Systems:
        Multiplayer games (track player scores, positions).
        Banking apps (remember user login sessions).
    - Stateless Systems:
        APIs (RESTful APIs are stateless).
        Static websites (no server-side memory of user interactions).
5. Highlight Pros and Cons
    - Stateful Systems:
        Pros: Can provide a seamless user experience.
        Cons: Require more resources (memory, storage) and are harder to scale.
    - Stateless Systems:
        Pros: Easier to scale and debug.
        Cons: May require additional mechanisms to maintain state (like cookies).

**Comment by hadrylouis** [comment]
While reviewing the MR, I noticed that no changes were made to the course material regarding the text about the concepts of stateless and stateful. Are you waiting for our feedback to potentially adjust the text afterward ?

Regarding the text proposed by ChatGPT, I find points 1, 2, and 3 to be perfectly accurate and well-presented. I don’t see what more could be explained. The basic concept is covered, with an analogy and then within the context of HTTP and TCP.

What would you like to change in the current text that you don't like, or what would you like to add ?

**Comment by ludelafo** [comment]
Exactly, no changes were made from last year (yet).

My main concern is the difficulty to state (no pun intended here) what a stateless/stateful application is.

A Dockerized Springboot application with a SQLite database would be considered stateful. However, the same Springboot application with a separated Postgres database would be considered stateless: the backend could be restarted without data loss and thus considered stateless.

A calculation server would be considered stateless if the calculations are made on the spot (you get the results immediately) but stateful if you had to come back to get the results once they are done.

I find the current state of the course material laking a bit of the main differences and when one is truly stateful and the other truly stateless.

**Comment by ludelafo** [comment]
I think I did find a formulation to make this topic more accessible. Let me know what you think!

**Comment by hadrylouis** [comment]
I think this formulation is simple and sufficient

**Review by hadrylouis — APPROVED** [review]

**Pull request merged**
